### PR TITLE
Fix NPE caused by unset `productFlowPriority`

### LINKED ISSUE #153: NullPointerException when login via SSO without setting product flow priority
Library version: **0.10.0**

Repro steps, stacktrace, screenshots: 

1. Assign any application's certificate footprint in uber developer's settings to enable SSO.
2. Integrate the sdk in your project
3. call `LoginManager.login()`

Expected Behavior: launching of Uber app with login activity

Real result: NPE crash

```
java.lang.NullPointerException: collection == null
        at java.util.ArrayList.<init>(ArrayList.java:94)
        at com.uber.sdk.android.core.auth.LoginManager.login(LoginManager.java:180)
```

The cause is the default value of `productFlowPriority` collection which is `null` and therefore while constructing `ArrayList` it crashes the app.

I would like to know if it's ok to pass to `setProductFlowPriority()` `Collections.emptyList()` to bypass the crash ?

### PR DESCRIPTION
**Pull request by thepoofy**
Fixed #153
Verified by unit tests.

Description:  Lack of an initial value caused a NPE when `LoginManager#login(Activity)` was invoked.

Related issue(s):  #153

### CODE REVIEW

File: core-android/src/main/java/com/uber/sdk/android/core/auth/LoginManager.java [hunk 1]
```diff
@@ -178,7 +179,7 @@ public void login(final @NonNull Activity activity) {
         if (ssoDeeplink.isSupported(SsoDeeplink.FlowVersion.REDIRECT_TO_SDK)) {
             Intent intent = LoginActivity.newIntent(
                     activity,
-                    new ArrayList<>(productFlowPriority),
+                    productFlowPriority,
```
Comment (thepoofy) [inline core-android/src/main/java/com/uber/sdk/android/core/auth/LoginManager.java]: No longer necessary to wrap this in a new ArrayList since we are only storing defensive copy ArrayLists.

File: core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java [hunk 2]
```diff
@@ -160,6 +161,27 @@ public void login_withRedirectToSdkFlowSsoSupported_shouldLoginActivityWithSsoPa
...
+        ArgumentCaptor<Intent> intentCaptor = ArgumentCaptor.forClass(Intent.class);
+        ArgumentCaptor<Integer> codeCaptor = ArgumentCaptor.forClass(Integer.class);
+
+        verify(activity).startActivityForResult(intentCaptor.capture(), codeCaptor.capture());
+
+        final Intent resultIntent = intentCaptor.getValue();
+        validateLoginIntentFields(resultIntent, supportedAppTypes, sessionConfiguration,
+                ResponseType.TOKEN, false, true, true);
+        assertThat(codeCaptor.getValue()).isEqualTo(REQUEST_CODE_LOGIN_DEFAULT);
+    }
```
Comment (thepoofy) [inline core-android/src/test/java/com/uber/sdk/android/core/auth/LoginManagerTest.java]: This test proved a NPE would be thrown by original code.

**Comment by jck2** [comment]
Good catch!
